### ISSUE TITLE
Clairifcation 

### ISSUE THREAD

**Issue by heroiclord** [DarthFly/advhd_ws2_tools#1]
Hi dev, just want to thank the work in making a compiler with instructions on running.

Some questions as I am stuck between requirements and usage (on win 10).
1) Are your github files extracted supposed to be in a separate folder or together with ws2 files and/or the php8 folder?

2) Where should cmd with php be run? Just from start menu, or from windows explorer url?

3) Attempting to run php decompile line in cmd leads to this error (I am using the php.exe as example, but errors are the same)
![php error](https://github.com/DarthFly/advhd_ws2_tools/assets/152635117/773aac75-8eec-485d-b85f-e85767c93f0a)
I have already remove ; on the extension=mbstring line in the php.ini file through notepad

4) arc_compile.php in your guide is now [arc_pack.php](https://github.com/DarthFly/advhd_ws2_tools/blob/master/arc_pack.php) right?

Appreciate further guidance, thank you and sorry for basic questions.

**Comment by DarthFly** [comment]
> Are your github files extracted supposed to be in a separate folder or together with ws2 files and/or the php8 folder?
It's up to you. `php ws2_decompile.php ..\path\to\arc_folder 1.0` or `php ws2_decompile.php c:/game/ 1.0|1.4|1.9`

> Where should cmd with php be run? Just from start menu, or from windows explorer URL?
Steps 5-6 of "Requirements". If you register PHP as global, you can run it from any folder as `php c:/scripts/ws2_decompile.php`. If not - you will need to specify full path to php.exe and then path to the script file from current folder `C:/php/php.exe ws2_decompile.php`

It's easier to run from scripts folder.

> arc_compile.php in your guide is now [arc_pack.php](https://github.com/DarthFly/advhd_ws2_tools/blob/master/arc_pack.php) right?
My bad, right..
